### ISSUE TITLE
Avoid printing of table content

### ISSUE THREAD

**Issue by tischi** [tlabs-data/tablesaw-parquet#75]
When running below code it prints the table content to the console. Can one suppress this?

```
TablesawParquet.register();
final TablesawParquetReadOptions readOptions = TablesawParquetReadOptions.builder( "/Users/tischer/Desktop/default.parquet" ).build();
final Table rows = Table.read().usingOptions( readOptions );
```

```
...
08:53:48.793 [main] DEBUG org.apache.parquet.hadoop.InternalParquetRecordReader - read value:                                 /Users/tischer/Desktop/default.parquet                                
 cellID  |  geneID  |  regionID  |     x      |     y      |  z  |  seeds  |  intensity  |  spot_id  |
------------------------------------------------------------------------------------------------------
```

**Comment by ccleva** [comment]
Hi @tischi, good point, thanks for your feedback.

While tablesaw-parquet itself logs very little information (maybe even too little), the underlying parquet reader from apache logs the file content at DEBUG level. You should configure your logging framework to record only INFO or WARN level for `org.apache.parquet.hadoop.InternalParquetRecordReader`.

The configuration line for log4j is:
```
log4j.logger.org.apache.parquet.hadoop.InternalParquetRecordReader=INFO
```
I will add this to the documentation. Thanks again.

**Comment by tischi** [comment]
Thanks! I cannot find this class: `InternalParquetRecordReader`
Do I need to add another dependency to the pom?

**Comment by ccleva** [comment]
It is already included in tablesaw-parquet as a dependency in the pom:
```
    <dependency>
      <groupId>org.apache.parquet</groupId>
      <artifactId>parquet-hadoop</artifactId>
      <version>${parquet.version}</version>
    </dependency>
```
The library version can change depending on the version of tablesaw-parquet you are using.

**Comment by tischi** [comment]
Could it be that I need to add a `log4j` dependency?

<img width="850" alt="image" src="https://user-images.githubusercontent.com/2157566/196722459-45056ca2-d992-4b9f-96c4-b0c2ef52c3b0.png">

**Comment by ccleva** [comment]
Sorry I was not clear: you probably have a `log4j.properties` file in the classpath or a log4j configuration done somewhere in your code (otherwise you would get a warning message and nothing would be logged) . You have to add this configuration line to this `log4j.properties` file to set the logging level of `InternalParquetRecordReader` to `INFO` and not log the file content (or modify the configuration code to that effect):
```
log4j.logger.org.apache.parquet.hadoop.InternalParquetRecordReader=INFO
```
Thanks to your comment I identified an issue with the current build: I missed a binding for slf4j that should have been excluded from a transitive dependency. This will be fixed in the next release.

Let me know if that answers your question.

**Comment by tischi** [comment]
Is there a way to do this purely programmatically?

I cannot locate the `log4j.properties` file (and I am also working in a collaborative settings where I think I should not ship such a file).

**Comment by ccleva** [comment]
Yes you can do it programmatically, you can check the [documentation for log4j 2](https://logging.apache.org/log4j/2.x/index.html) if this is the one you are using.

If you are in a collaborative setting, I would suggest you first check with the other developers about the current logging framework and configuration - as I said you must already have a configuration somewhere otherwise it would not log anything.

**Comment by lucky-wh** [comment]
Excuse me, how do I remove this log output from springboot?

**Comment by ccleva** [comment]
Hi @lucky-wh. There are several ways to configure spring-boot logging. If you set the logging levels in the `application.properties` file, the following line is enough to avoid data leaking in the logs:
```
logging.level.org.apache.parquet.hadoop.InternalParquetRecordReader=INFO
```

**Comment by tischi** [comment]
For reference, this is what worked for me:

```
ch.qos.logback.classic.Logger logger = ( Logger ) LoggerFactory.getLogger("org.apache.parquet.hadoop.InternalParquetRecordReader");
logger.setLevel( Level.OFF );
```
